### ISSUE TITLE
Не постятся клипы с ну че там

### ISSUE THREAD

**Issue by Akiyamov** [Akiyamov/vk-to-telegram-go#1]
```go
2024/08/17 21:13:34 [INFO] First request.
2024/08/17 21:14:13 [INFO] New post vk.com/wall-201104273_16875
2024/08/17 21:14:14 [INFO] GetVideoURL 1: status Code: 200
2024/08/17 21:14:14 [INFO] status Code: 200
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.GetVideoURL(0xfffffffff403646f, 0x1b31b1e5)
        /build/main.go:281 +0x2238
main.PostMessage({0x4000118480?, {0x400029d008?, 0x2?, 0x400056bdd8?}})
        /build/main.go:367 +0x564
main.Request()
        /build/main.go:97 +0x554
main.Poll()
        /build/main.go:434 +0xec
main.main()
        /build/main.go:466 +0x2c8
```

**Comment by Akiyamov** [comment]
Проблема была в конфиге
